<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="10.0.1">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="DotNetSeleniumExtras.PageObjects" Version="3.11.0" />
		<PackageReference Include="DotNetSeleniumExtras.PageObjects.Core" Version="4.14.1" />
		<PackageReference Include="DotNetSeleniumExtras.PageObjects.Core.Linq" Version="1.0.0" />
		<PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
		<PackageReference Include="NLog" Version="6.1.4" />
		<PackageReference Include="NLog.Config" Version="4.7.15" />
		<PackageReference Include="NLog.Extensions.Logging" Version="6.1.4" />
		<PackageReference Include="NUnit" Version="4.6.1" />
		<PackageReference Include="NUnit.Analyzers" Version="4.14.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
		<PackageReference Include="Selenium.Support" Version="4.45.0" />
		<PackageReference Include="Selenium.WebDriver" Version="4.45.0" />
		<PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="150.0.7871.181" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="NUnit.Framework" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.10" />
	</ItemGroup>

	<ItemGroup>
		<None Update="NLog.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>